// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: cart.proto

package server

import (
	"context"

	"github.com/HBUzxl/douyin-mall/cart/cart"
	"github.com/HBUzxl/douyin-mall/cart/internal/logic"
	"github.com/HBUzxl/douyin-mall/cart/internal/svc"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	cart.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

// 获取购物车
func (s *CartServer) GetCart(ctx context.Context, in *cart.GetCartReq) (*cart.GetCartResp, error) {
	l := logic.NewGetCartLogic(ctx, s.svcCtx)
	return l.GetCart(in)
}

// 清空购物车
func (s *CartServer) ClearCart(ctx context.Context, in *cart.ClearCartReq) (*cart.ClearCartResp, error) {
	l := logic.NewClearCartLogic(ctx, s.svcCtx)
	return l.ClearCart(in)
}

// 添加商品到购物车
func (s *CartServer) AddProductToCart(ctx context.Context, in *cart.AddProductToCartReq) (*cart.AddProductToCartResp, error) {
	l := logic.NewAddProductToCartLogic(ctx, s.svcCtx)
	return l.AddProductToCart(in)
}
