// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: auth.proto

package server

import (
	"context"

	"github.com/HBUzxl/douyin-mall/auth/auth"
	"github.com/HBUzxl/douyin-mall/auth/internal/logic"
	"github.com/HBUzxl/douyin-mall/auth/internal/svc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

// 分发token
func (s *AuthServer) DeliverTokenByRpc(ctx context.Context, in *auth.DeliverTokenReq) (*auth.DeliverTokenResp, error) {
	l := logic.NewDeliverTokenByRpcLogic(ctx, s.svcCtx)
	return l.DeliverTokenByRpc(in)
}

// 刷新token
func (s *AuthServer) RefreshTokenByRpc(ctx context.Context, in *auth.RefreshTokenReq) (*auth.DeliverTokenResp, error) {
	l := logic.NewRefreshTokenByRpcLogic(ctx, s.svcCtx)
	return l.RefreshTokenByRpc(in)
}
