// Code generated by goctl. DO NOT EDIT.
// Source: eino.proto

package einoclient

import (
	"context"

	"eino/eino"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = eino.Request
	Response = eino.Response

	Eino interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultEino struct {
		cli zrpc.Client
	}
)

func NewEino(cli zrpc.Client) Eino {
	return &defaultEino{
		cli: cli,
	}
}

func (m *defaultEino) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := eino.NewEinoClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
