// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: order.proto

package server

import (
	"context"

	"github.com/HBUzxl/douyin-mall/order/internal/logic"
	"github.com/HBUzxl/douyin-mall/order/internal/svc"
	"github.com/HBUzxl/douyin-mall/order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// 获取用户订单
func (s *OrderServer) GetUserOrders(ctx context.Context, in *order.GetUserOrdersReq) (*order.GetUserOrdersResp, error) {
	l := logic.NewGetUserOrdersLogic(ctx, s.svcCtx)
	return l.GetUserOrders(in)
}

// 更新订单地址
func (s *OrderServer) UpdateOrderAddress(ctx context.Context, in *order.UpdateOrderAddressReq) (*order.UpdateOrderAddressResp, error) {
	l := logic.NewUpdateOrderAddressLogic(ctx, s.svcCtx)
	return l.UpdateOrderAddress(in)
}

// 获取订单信息
func (s *OrderServer) GetOrder(ctx context.Context, in *order.GetOrderReq) (*order.GetOrderResp, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}
