// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AddProductToCartReq struct {
	Item CartItem `json:"item"`
}

type AddProductToCartResp struct {
	Item CartItem `json:"item"`
}

type ClearCartReq struct {
}

type ClearCartResp struct {
	UserUuid string `json:"user_uuid"`
}

type GetCartReq struct {
	UserUuid string `json:"user_uuid"`
}

type GetCartResp struct {
	Total     int64      `json:"total"`
	CartItems []CartItem `json:"cart_items"`
}
