// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetUserOrdersReq struct {
}

type GetUserOrdersResp struct {
	Orders []Order `json:"orders"`
	Total  int64   `json:"total"`
}
