// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetUserOrdersReq struct {
}

type GetUserOrdersResp struct {
	Orders []Order `json:"orders"`
	Total  int64   `json:"total"`
}

type UpdateOrderAddressReq struct {
	OrderUuid   string `json:"order_uuid"`
	AddressUuid string `json:"address_uuid"`
}

type UpdateOrderAddressResp struct {
	Success bool `json:"success"`
}
