// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateProductReq struct {
	Name        string `json:"name"`
	Price       int64  `json:"price"`
	Stock       int64  `json:"stock"`
	Description string `json:"description"`
}

type CreateProductResp struct {
	Product Product `json:"product"`
}

type DeleteProductReq struct {
	Uuid string `json:"uuid"`
}

type DeleteProductResp struct {
	Uuid string `json:"uuid"`
}

type GetProductReq struct {
	Uuid string `form:"uuid"`
}

type GetProductResp struct {
	Product Product `json:"product"`
}

type UpdateProductReq struct {
	Product Product `json:"product"`
}

type UpdateProductResp struct {
	Product Product `json:"product"`
}
