// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateProductReq struct {
	Name        string `json:"name"`
	Price       int64  `json:"price"`
	Stock       int64  `json:"stock"`
	Description string `json:"description"`
}

type CreateProductResp struct {
	Product Product `json:"product"`
}
