// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type LogoutReq struct {
}

type LogoutResp struct {
	Ok bool `json:"ok"`
}

type RefreshTokenReq struct {
	RefreshToken string `form:"refresh_token"`
}

type RefreshTokenResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Email           string `form:"email"`
	Password        string `form:"password"`
	ConfirmPassword string `form:"confirm_password"`
}

type RegisterResp struct {
	UserUuid string `json:"user_uuid"`
}
