// Code generated by goctl. DO NOT EDIT.
// Source: eino.proto

package server

import (
	"context"

	"eino/eino"
	"eino/internal/logic"
	"eino/internal/svc"
)

type EinoServer struct {
	svcCtx *svc.ServiceContext
	eino.UnimplementedEinoServer
}

func NewEinoServer(svcCtx *svc.ServiceContext) *EinoServer {
	return &EinoServer{
		svcCtx: svcCtx,
	}
}

func (s *EinoServer) Ping(ctx context.Context, in *eino.Request) (*eino.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
