// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	test "douyin-mall/atlas/internal/handler/test"
	"douyin-mall/atlas/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// test
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: test.PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
