// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: order.proto

package order_client

import (
	"context"

	"github.com/HBUzxl/douyin-mall/order/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserOrdersReq  = order.GetUserOrdersReq
	GetUserOrdersResp = order.GetUserOrdersResp
	OrderInfo         = order.OrderInfo
	OrderItem         = order.OrderItem

	Order interface {
		// 获取用户订单
		GetUserOrders(ctx context.Context, in *GetUserOrdersReq, opts ...grpc.CallOption) (*GetUserOrdersResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// 获取用户订单
func (m *defaultOrder) GetUserOrders(ctx context.Context, in *GetUserOrdersReq, opts ...grpc.CallOption) (*GetUserOrdersResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetUserOrders(ctx, in, opts...)
}
