// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: order.proto

package order_client

import (
	"context"

	"github.com/HBUzxl/douyin-mall/order/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserOrdersReq       = order.GetUserOrdersReq
	GetUserOrdersResp      = order.GetUserOrdersResp
	OrderInfo              = order.OrderInfo
	OrderItem              = order.OrderItem
	UpdateOrderAddressReq  = order.UpdateOrderAddressReq
	UpdateOrderAddressResp = order.UpdateOrderAddressResp

	Order interface {
		// 获取用户订单
		GetUserOrders(ctx context.Context, in *GetUserOrdersReq, opts ...grpc.CallOption) (*GetUserOrdersResp, error)
		// 更新订单地址
		UpdateOrderAddress(ctx context.Context, in *UpdateOrderAddressReq, opts ...grpc.CallOption) (*UpdateOrderAddressResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// 获取用户订单
func (m *defaultOrder) GetUserOrders(ctx context.Context, in *GetUserOrdersReq, opts ...grpc.CallOption) (*GetUserOrdersResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetUserOrders(ctx, in, opts...)
}

// 更新订单地址
func (m *defaultOrder) UpdateOrderAddress(ctx context.Context, in *UpdateOrderAddressReq, opts ...grpc.CallOption) (*UpdateOrderAddressResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.UpdateOrderAddress(ctx, in, opts...)
}
