// Code generated by goctl. DO NOT EDIT.
// Source: checkout.proto

package server

import (
	"context"

	"checkout/checkout"
	"checkout/internal/logic"
	"checkout/internal/svc"
)

type CheckoutServer struct {
	svcCtx *svc.ServiceContext
	checkout.UnimplementedCheckoutServer
}

func NewCheckoutServer(svcCtx *svc.ServiceContext) *CheckoutServer {
	return &CheckoutServer{
		svcCtx: svcCtx,
	}
}

func (s *CheckoutServer) Ping(ctx context.Context, in *checkout.Request) (*checkout.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
