// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: eino.proto

package eino

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Eino_Ping_FullMethodName = "/eino.Eino/Ping"
)

// EinoClient is the client API for Eino service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EinoClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type einoClient struct {
	cc grpc.ClientConnInterface
}

func NewEinoClient(cc grpc.ClientConnInterface) EinoClient {
	return &einoClient{cc}
}

func (c *einoClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Eino_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EinoServer is the server API for Eino service.
// All implementations must embed UnimplementedEinoServer
// for forward compatibility
type EinoServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedEinoServer()
}

// UnimplementedEinoServer must be embedded to have forward compatible implementations.
type UnimplementedEinoServer struct {
}

func (UnimplementedEinoServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEinoServer) mustEmbedUnimplementedEinoServer() {}

// UnsafeEinoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EinoServer will
// result in compilation errors.
type UnsafeEinoServer interface {
	mustEmbedUnimplementedEinoServer()
}

func RegisterEinoServer(s grpc.ServiceRegistrar, srv EinoServer) {
	s.RegisterService(&Eino_ServiceDesc, srv)
}

func _Eino_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EinoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Eino_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EinoServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Eino_ServiceDesc is the grpc.ServiceDesc for Eino service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Eino_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eino.Eino",
	HandlerType: (*EinoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Eino_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eino.proto",
}
